name: "Build PDF for Pull Request"
on:
  pull_request:
    branches:
      - main
jobs:
  build-tex-sources:
    name: 'Build TeX Sources'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build PDF document
        run: make PDFOUT_BASENAME=resume-pr pdf
      - name: Publish PDF
        if: ${{ github.event_name == 'pull_request' }}
        uses: gavv/pull-request-artifacts@v1.0.0
        with:
          commit: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifacts-branch: artifacts
          artifacts: ./src/resume-pr.pdf

